language: cpp

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-9']
      env: COMPILER=g++-9
    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.9']
          packages: ['clang-3.9']
      env: COMPILER=clang++-3.9

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq cmake

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER ..
  - cmake --build .
  - ctest --output-on-failure
