image: Visual Studio 2019

platform:
  - x64

configuration:
  - Debug
  - Release

install:
  - cmake --version

build_script:
  - mkdir build
  - cd build
  - cmake -G "Visual Studio 16 2019" -A x64 ..
  - cmake --build . --config %CONFIGURATION%

test_script:
  - ctest -C %CONFIGURATION% --output-on-failure
